# Generated by Django 5.2.9 on 2025-12-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ram_total', models.BigIntegerField(help_text='Total RAM in bytes')),
                ('ram_used', models.BigIntegerField(help_text='Used RAM in bytes')),
                ('ram_free', models.BigIntegerField(help_text='Free RAM in bytes')),
                ('cpu_percent', models.FloatField(help_text='CPU usage percentage')),
                ('disk_total', models.BigIntegerField(help_text='Total disk space in bytes')),
                ('disk_used', models.BigIntegerField(help_text='Used disk space in bytes')),
                ('disk_free', models.BigIntegerField(help_text='Free disk space in bytes')),
                ('raw_data', models.JSONField(default=dict, help_text='Original JSON message from Kafka')),
            ],
            options={
                'db_table': 'system_status',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='system_stat_timesta_dfffb1_idx')],
            },
        ),
    ]
